name: Deploy Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Existing tag to be released, e.g. v1.2.3, v2.2.2, v3.0.0'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy release
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2.0.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Get Secrets
        uses: aws-actions/aws-secretsmanager-get-secrets@v1
        with:
          secret-ids: |
            DEVOPS_GITHUB_TOKEN,CN/DEVOPS_GITHUB_TOKEN

      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Update version and create a new tag
        run: |
          git config user.email "devopshelm@hazelcast.com"
          git config user.name "devOpsHelm"
          TAG="${{ github.event.inputs.tag }}"
          mvn versions:set -DnewVersion=${TAG:1}
            if [[ -n $(git status -s) ]]; then
              git add pom.xml
              git commit -m "Updated version to '${TAG:1}'"
              git push -u origin master
            fi
          git tag ${TAG}
          git push origin ${TAG}
          echo "TAG=${TAG}" >> $GITHUB_ENV
          echo "VERSION=${TAG:1}" >> $GITHUB_ENV

      - uses: actions/checkout@v3
        with:
          fetch-tags: true
          ref: "${{ env.TAG }}"

